---
title: "Multiple Testing"
author: "Livio Finos"
highlighter: highlight.js
output:
  pdf_document:
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
job: University of Padua
license: by-nc-sa
mode: selfcontained
hitheme: tomorrow
subtitle: Homework week 20
framework: io2012
widgets: []
---

# FDR corrected p-values

Given the following p-values
```{r,echo=FALSE}
set.seed(1)
ps=round(rbeta(10,1,10),4)

# p.adjust(ps,method = "BH")
cat(ps,sep=", ")
```

- compute the adjusted p-values using Benjamini-Hochberg (FDR controlling) procedure ans show the steps needed.
- run the analysis using `p.adjust` and verify that you get the same results.


# Dose Response/Selection Study in GERD Patients 

Description:  
<http://webserv.jcu.edu/math//faculty/TShort/Bradstreet/part1/part1-table3.html>

Twelve Gastroesophageal Reflux Disease (GERD) patients were allocated randomly to one of four treatment sequences of 0 (placebo), 10, 20, and 40 mg a.m. of a drug in a four period crossover design. On the fifth (last) day of each treatment period and the study baseline period, percent reflux time (% RT), the number of reflux episodes per hour (# EPS/HR), and the number of reflux episodes greater than five minutes in a 12 hour period (#EPS > 5'/12 HR) were recorded for each patient using ambulatory 24-hour esophageal pH monitoring. Measurements were taken while the patient was in the upright (U) or supine (S) positions. The time (hours) in the upright and supine positions was recorded. A seven day washout period separated the treatment periods. The data recorded in the upright and supine positions are shown in Table 3.

dataset:  
<http://webserv.jcu.edu/math//faculty/TShort/Bradstreet/part1/Bradp1t3.txt>

## Define a procedure (one enpoint)  
Let consider for the moment, only the % RT endpoint, only upright (U) position and
the comparisons:  

- $H_{10}: \mu_0 = \mu_{10}$
- $H_{20}: \mu_0 = \mu_{20}$
- $H_{40}: \mu_0 = \mu_{40}$

In order to know if there is a dose response and which doses are effective, define an appropriate multiple testing procedure.
Define the procedure in such a way that:  

- $\alpha/2$ is splitted among the three comparisons 
- the remaining $\alpha/2$ is allocated to the comparison 0 (placebo) vs 40
- when one hypothesis is rejected, its $\alpha$ is inherited in a backward fashion: ($H_{40}$ to $H_{20}$ and $H_{20}$ to $H_{10}$)

Is there any room for a further improvement of the procedure? if yes, make your proposal.

## Define a procedure (three enpoints)
Define now a procedure that considers also the endpoints: \#EPS/HR and \#EPS > 	5'/12HR (i.e. 3 doses comparisons, 3 endpoints)

## Analyse the data
Analyses the data using the procedures defined at points 2.1 and 2.2.

