---
title: "Multiple Testing"
author: "Livio Finos"
highlighter: highlight.js
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
job: University of Padua
license: by-nc-sa
mode: selfcontained
hitheme: tomorrow
subtitle: Homework week 18
framework: io2012
widgets: []
---


# Simulation

Perform a simulation with the following setting:

- n = 8 abservations (two balanced samples)
- m = 20 endpoints
- m1=5 of them are different between the two groups (H1 hypotheses).
- control group is distributed as N(0,1) and drug group is N(0,1) for H0 endpoints, while N(3,1) for H1 ones.
- all endpoints are tested with a t-test
- 1000 replications

For each generation of data compute 

- the realized FWER (at least one rejection among the H0s)
- the power (proportion of rejected H1 hypotheses)
- testin individual hypotheses at level `alpha_a=.05` and `alpha_b=1-(1-.05)^(1/m)`


After the simulation, answer the following questions:

- Does `alpha_a=.05` controls the the FWER at level `0.05`?
- Does `alpha_b=1-(1-.05)^(1/m)` controls the the FWER at level `0.05`?
- What is the power of test controlled at level `alpha_b=1-(1-.05)^(1/m)`?
- What is the power of test controlled at level `alpha_a=.05`? Would you prefer this method to the one above (i.e. `alpha_b=1-(1-.05)^(1/m)`)?
